### ISSUE TITLE
Introduce special treatment for singletons

### ISSUE THREAD

**Issue by stefan11** [langsci/langsci-avm#21]
![grafik](https://user-images.githubusercontent.com/4655859/81474926-efdf3d80-9208-11ea-9e52-a91a03a4f76e.png)

```latex
\avm{
			[subj  & \1 \\
			 comps & \2 \- list(gap-ss) \\
			 deps  & < \1 > \+ \2
			]
		}
```

**Comment by kopeckyf** [comment]
This is the indented behaviour and not a bug. Every delimiter produces a new (sub-)structure. If you don't want to have structures but parenthetical remarks, you need to use escaping, as in `list !(gap-ss)!`.

**Comment by stefan11** [comment]
But even if this is structure, the question would then be: what is a single feature name. This is not well-formed. If it is a single unit it could only be a type and hence it should be italics.

```latex
list(gap-ss)
```
is a list of types. The same is true for ```NP[nom]```. ```nom``` is a value. Right now I type it as ```NP[\type{nom}]```, but it would be cool to be able to write ```NP[nom]```.

If this were the final decision, you have to list this as thing to do for converting avm.sty to langsci.sty.

**Comment by kopeckyf** [comment]
> If it is a single unit it could only be a type and hence it should be italics.

Computers can't think and in particular they don't possess any knowledge on linguistic theory. It will take some time to investigate whether there is an automatic solution that does not imply too much computation time.

**Comment by stefan11** [comment]
I know that computers can't think. But we can think and we can tell them what to do. I think the generalization is that if we have a single object "atom" it will be a value to be typeset in value font. As soon as we have the first pair "feature & value", we are in AVM mode and have to care for alignment and feature will be in feature font and value in value font. Would be great if this could be done.

**Comment by kopeckyf** [comment]
You can't think about TeX programming with the kind of "objects" you have in mind. When programming TeX, you need a procedually oriented mindeset rather than a descriptive one.

Anyway, the candidate function to solve this issue would be `\peek_catcode_collect_inline:Nn` from `l3experimental`. However, it has a major drawback, which is that it gobbles spaces. Will have to see whether we program a custom recursion function to peek ahead at the complete contents of a single line.

As of now, this issue is on hold.

**Comment by kopeckyf** [comment]
With https://github.com/langsci/langsci-avm/commit/96051f980d1a01afb6092e475f037eadb5fea9e6, this is easy:

```
\avmdefinecommand {list}[list]*{ attributes=\normalfont } % define a new \list command
   % Note: the label "list" will be out put in whatever font is currently active.

\avm{
	[subj  & \1 \\
	comps & \2 \- \list (gap-ss) \\ % Produce a \list
	deps  & < \1 > \+ \2
	]
}
```
Note: in this example, as `\list` is in the second column, the label "list" will be output in the current font, which is `\itshape` by default.

[Edit: The `*` is important in `\avmdefinecommand` so that there is no column separation between the label and the following structure]

Result:
![liste](https://user-images.githubusercontent.com/10461729/85590872-120c0e00-b645-11ea-809d-13a607213e93.png)

**Comment by kopeckyf** [comment]
Please report any further comments/questions regarding this issue under #2.
