### ISSUE TITLE
Too much space between \1 and \+

### ISSUE THREAD

**Issue by stefan11** [langsci/langsci-avm#31]
<img width="530" alt="grafik" src="https://user-images.githubusercontent.com/4655859/86024139-e619cf80-ba2c-11ea-8866-f61ea63007df.png">

```latex
\avm{
[ arg-st \1 \+ \2 \+  < [ vform & ppp\\
                                      da    & < XP$_{ref}$ >\\
                                      spr   & \1\\
                                      comps & \2  ] > ] 
}
```

The space before \2 is smaller than the space after \2.

**Comment by kopeckyf** [comment]
Related: #22 #23  https://github.com/langsci/langsci-avm/commit/53eb2235f3073b66efe78c1ae05ef6c988aa22df

(Btw, @stefan11, the subscript of XP would be better represented as `_{\textit{ref}}` or `\textsuperscript{\itshape ref}`, because `_{ref}` places _ref_ in math mode, and then it means "the product of r times e times f" - as is visible in the kerning)
