### ISSUE TITLE
Emulate Fillmore & Kay's notation

### ISSUE THREAD

**Issue by AveryAndrews** [langsci/langsci-avm#37]
I was trying to use ![!, !]! to produce small square brackets, and this did not seem to work, got '!' combined with big brackets. 

UPDATE: the issue is caused by some kind of interaction with the \node command in a package I wrote once upon a time called pst-tree-dvips-emu.sty, which is a partial emulation of Emma Pease's tree.sty on top of pstricks, which supports drawing curved lines in various ways.  It can be evaded by using \newsavebox etc in the obvious way.

On a completely different issue, would it be possible to support construction grammar boxes, perhaps with [[ and ]]?

**Comment by kopeckyf** [comment]
It is now possible to use `\[ ... \]` for semantic brackets. 

There's a few caveats about this, which has to do with semantic brackets missing from LaTeX' internal delimiter definitions. They are not as readily available as other delimiters are. 

In short, please make sure that you have a document environment that supplies semantic brackets. Libertinus will do so, and the `langscibook` document class as well. If semantic brackets aren't provided, `langsci-avm` will automatically load the package `unicode-math` to make them available. To initialise all of this, please also load the package option `lfg`, i.e. `\usepackage[lfg]{langsci-avm}`.

Also, the maximum size of the semantic bracket will depend on the font in use.

Here's an example:

![example1](https://user-images.githubusercontent.com/10461729/94923826-c88d5380-04bc-11eb-80cf-73f0fd716ddb.png)

```
\avm{ 
  \[ 
    type & knight\\  
    [lives in & forest\\
     says & ``Ni''\\ 
     desires&shrubbery] 
  \]
}
```

**Comment by skalyan91** [comment]
@AveryAndrews Maybe if there was a way to get null delimiters, you could just wrap an AVM in `\fbox{}`; that would give you Construction Grammar boxes.

@kopeckyf What Avery was asking about was not double-brackets, but rather enclosing an AVM in a (four-sided) box rather than just left and right delimiters.

**Comment by kopeckyf** [comment]
Could you explain what the notation of not surrounding a matrix with delimiters, but putting it into a frame means?

**Comment by skalyan91** [comment]
It’s just a notational variant of square brackets, which happens to be used in Fillmore and Kay’s Construction Grammar.

**Comment by kopeckyf** [comment]
@skalyan91 Do you think it makes sense to preserve the notation from Fillmore & Kay's grammar? Wouldn't it make sense to adjust their notation to the commonly used square brackets?

**Comment by Glottotopia** [comment]
This is sensible from an engineering perspective, but in general, scientific communities don't work that way. Notational conventions have a certain iconic value and signal, among other things, allegiance to a particular school of thought, which implies much more than mere notational conventions.

**Comment by skalyan91** [comment]
@kopeckyf Arguably this is what Sign-Based Construction Grammar has done. But there is clearly still an audience for “classical” Construction Grammar, which would prefer to use boxes if these are available.

**Comment by AveryAndrews** [comment]
@kopeckyf Adding to what Siva says, I think this notation has great intuitive appeal to many people, due (I suspect) to its geometrical/topological evocation of plugging things into things; it is possible that not so many of them use LaTeX, but it would be useful to have for writing things for these people to read, so that they might not toss them into the bin within the first 3 minutes.

**Comment by kopeckyf** [comment]
Paused until #38 is resolved.

**Comment by kopeckyf** [comment]
Apologies for the long time you had to wait. It is now possible to use `\lframe` and `\rframe` as delimiters. Since these are non-standard ways of delimiting contents, I came up with these words. The expressions `\lframe` and `\rframe` do not take any arguments, and you can use them as you would any other delimiter.

Example:
```latex
\avm{
  \lframe Hello & World \rframe
}
```

There is more information in the [documentation](https://github.com/langsci/langsci-avm/blob/master/langsci-avm.pdf). Please use the most recent [`.sty` file](https://github.com/langsci/langsci-avm/blob/master/langsci-avm.sty) to use this new delimiter. It may take some time before the new version arrives on CTAN.
